name: "organize-contributors"
description: "GitHub Action organize-contributors"
author: "thinkasany"
branding:
  icon: "check-circle"
  color: "gray-dark"
inputs:
  github_token:
    description: Your GitHub token for authentication.
    required: true

  pr_number:
    description: "your pr number"
    required: true

  team_label:
    description: "your team label"
    default: "Core Team" 
  
  enable_team_label:
    description: "enabled by default"
    default: "true" 
  
  enable_suffix:
    description: "enabled by default"
    default: "true" 


outputs:
  result:
    description: "The result of api"
runs:
  using: node16
  main: 'dist/index.js'
